# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://jannikhuels.github.io/rh-web/"
languageCode = "de-DE"
title = "Ingenieurbüro Richters & Hüls"
publishDir = "docs"

# Metadata
[params]
  author = "Ingenieurbüro Richters & Hüls"
  description = "Experten für Planung, Messung, Gutachten und Beratung im Immissionsschutz."

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "Ingenieurbüro für Immissionsschutz."
  description = "Schutz von Mensch und Umwelt."
  companylogo = "images/logo@2x.png"

# menu
[ menu ]
  [[ menu.main ]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[ menu.main ]]
    name = "Leistungen"
    url = "/leistungen/"
    identifier = "leistungen"
    weight = 2
  [[ menu.main ]]
    name = "Team"
    url = "/team/"
    identifier = "team"
    weight = 3
  [[ menu.main ]]
    name = "Jobs"
    url = "/jobs/"
    identifier = "jobs"
    weight = 4
  [[ menu.main ]]
    name = "Kontakt"
    url = "/kontakt/"
    identifier = "kontakt"
    weight = 5

# Navigation section
[params.nav]
  mission = "Informationen"
  services = "Überblick"
  team = "Über uns"
  contact = "Kontakt"
  jobs = "Jobs"
  # Include logo instead if HOME:
  logo = "images/logo-small@2x.png"
  [[params.nav.external]]
    name = "Leistungen"
    link = "leistungen"
  [[params.nav.external]]
    name = "Team"
    link = "team"
  [[params.nav.external]]
    name = "Jobs"
    link = "jobs"
  [[params.nav.external]]
    name = "Kontakt"
    link = "kontakt"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  companyname = "Ingenieurbüro Richters & Hüls"
  street = "Erhardstraße 9"
  city = "48683 Ahaus"
  firsttelephone = "+49 2561 43003"
  secondtelephone = "+49 2561 43004"
  fax = "+49 2561 43005"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"

[params.contact]
  enable = false
  title = "Kontakt"
  message = "Nichts ist uns wichtiger als der persönliche Kontakt."
  name_placeholder = "Name"
  email_placeholder = "eMail"
  email_disclaimer = "Wir werden keine Informationen mit Dritten teilen."
  message_placeholder = "Nachricht."
  button_text = "Absenden"
  